import { PAGES_PREFIX_PATH } from 'constants/route.constant'
import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
} from 'constants/navigation.constant'
import { ADMIN, SUPER_ADMIN, USER } from 'constants/roles.constant'

const pagesNavigationConfig = [
    {
        key: 'pages',
        path: '',
        title: '',
        translateKey: '',
        icon: 'pages',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [SUPER_ADMIN, ADMIN, USER],
        subMenu: [
            {
                key: 'pages.analytis',
                path: ``,
                title: 'Analytics',
                translateKey: 'nav.pages.analytis',
                icon: 'welcome',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [SUPER_ADMIN, ADMIN, USER],
                subMenu: [
                    {
                        key: 'pages.analytis.input',
                        path: `pages/analytics/input`,
                        title: 'Input',
                        translateKey: 'nav.pages.analytis_input',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [SUPER_ADMIN, ADMIN],
                        subMenu: [],
                    },
                    {
                        key: 'pages.analytis.output',
                        path: `pages/analytics/output`,
                        title: 'output',
                        translateKey: 'nav.pages.analytis_output',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [SUPER_ADMIN, ADMIN],
                        subMenu: [],
                    },
                    // {
                    //     key: 'pages.analytis.metadata',
                    //     path: `pages/analytics/metadata`,
                    //     title: 'Metadata',
                    //     translateKey: 'nav.pages.analytis_metadata',
                    //     icon: '',
                    //     type: NAV_ITEM_TYPE_ITEM,
                    //     authority: [ADMIN, USER],
                    //     subMenu: [],
                    // },
                    // {
                    //     key: 'pages.analytis.detail',
                    //     path: `pages/analytis/detail/:id`,
                    //     title: 'detail',
                    //     translateKey: '',
                    //     icon: '',
                    //     type: NAV_ITEM_TYPE_ITEM,
                    //     authority: [ADMIN, USER],
                    //     subMenu: [],
                    // }
                ],
            },
            {
                key: 'pages.global',
                path: `pages/global`,
                title: 'Global',
                translateKey: 'nav.pages.global',
                icon: 'welcome',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [SUPER_ADMIN, ADMIN, USER],
                subMenu: [],
            },
            {
                key: 'pages.vertical_keyword',
                path: `pages/vertical-keyword`,
                title: 'Vertical Keyword',
                translateKey: 'nav.pages.vertical_keyword',
                icon: 'welcome',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [SUPER_ADMIN, ADMIN, USER],
                subMenu: [],
            },  
            {
                key: 'pages.follower_group',
                path: `pages/follower-group`,
                title: 'Follower Group',
                translateKey: 'nav.pages.follower_group',
                icon: 'welcome',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [SUPER_ADMIN, ADMIN, USER],
                subMenu: [],
            },
            {
                key: 'pages.follower_watch',
                path: `pages/follower-watch`,
                title: 'Follower Watch',
                translateKey: 'nav.pages.follower_watch',
                icon: 'welcome',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [SUPER_ADMIN, ADMIN, USER],
                subMenu: [],
            },
            {
                key: 'pages.user',
                path: `pages/user-management`,
                title: 'User Manager',
                translateKey: 'nav.pages.user_manager',
                icon: 'welcome',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [SUPER_ADMIN, ADMIN],
                subMenu: [],
            },
            {
                key: 'pages.change_pwd',
                path: `pages/user/change-pwd/:id`,
                title: 'Password',
                translateKey: 'nav.pages.password',
                icon: 'welcome',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [SUPER_ADMIN, ADMIN],
                subMenu: [],
            },
        ],
    },
]

export default pagesNavigationConfig
